const data = {
  products: [
    {
      _id: '1',
      name: 'aufwändig',
      category: 'Watches',
      image: './images/watch1.jpg',
      price: 900,
      brand: 'rolex',
      rating: 4.5,
      numReviews: 16,
      desciption: 'high quality product',
    },
    {
      _id: '2',
      name: 'Bettmümpfeli',
      category: 'Watches',
      image: './images/watch2.jpg',
      price: 800,
      brand: 'Audemars Piguet',
      rating: 3.5,
      numReviews: 12,
      desciption: 'excellent product',
    },
    {
      _id: '3',
      name: 'Hundsverlocheti',
      category: 'Watches',
      image: './images/watch3.jpg',
      price: 400,
      brand: 'Vacheron Constantin',
      rating: 4.0,
      numReviews: 15,
      desciption: 'professional watch',
    },
    {
      _id: '4',
      name: 'Feierabend',
      category: 'Watches',
      image: './images/watch4.jpg',
      price: 300,
      brand: 'Patek Philippe',
      rating: 4.0,
      numReviews: 14,
      desciption: 'best professional product',
    },
    {
      _id: '5',
      name: 'Schafseckel',
      category: 'Bracelets',
      image: './images/bracelet1.png',
      price: 800,
      brand: 'Blancpain',
      rating: 4.5,
      numReviews: 10,
      desciption: 'high quality bracelet',
    },
  ],
  };
export default data;
